import {
    Ban,
    BadgePercent,
    Banknote,
    Bike,
    Building2,
    ChefHat,
    Clock,
    ConciergeBell,
    FileText,
    FolderTree,
    History,
    Landmark,
    Package,
    Percent,
    PieChart,
    Receipt,
    Scale,
    ScrollText,
    Store,
    Trash2,
    TrendingUp,
    Truck,
    Undo2,
    UserCog,
    UserRound,
    Utensils,
    UtensilsCrossed,
    Wallet,
    XCircle,
} from 'lucide-react';

/** Report card icons by the name the server sends (Report::icon()). */
const ICONS = {
    ban: Ban,
    'badge-percent': BadgePercent,
    banknote: Banknote,
    bike: Bike,
    'building-2': Building2,
    'chef-hat': ChefHat,
    clock: Clock,
    'concierge-bell': ConciergeBell,
    'folder-tree': FolderTree,
    history: History,
    landmark: Landmark,
    package: Package,
    percent: Percent,
    'pie-chart': PieChart,
    receipt: Receipt,
    scale: Scale,
    'scroll-text': ScrollText,
    store: Store,
    'trash-2': Trash2,
    'trending-up': TrendingUp,
    truck: Truck,
    'undo-2': Undo2,
    'user-cog': UserCog,
    'user-round': UserRound,
    utensils: Utensils,
    'utensils-crossed': UtensilsCrossed,
    wallet: Wallet,
    'x-circle': XCircle,
};

export default function reportIcon(name) {
    return ICONS[name] ?? FileText;
}
