import {
    LayoutDashboard,
    ShoppingCart,
    ClipboardList,
    LayoutGrid,
    ChefHat,
    FolderTree,
    UtensilsCrossed,
    Package,
    BadgePercent,
    Percent,
    ListPlus,
    Flame,
    Ruler,
    Wheat,
    History,
    FileText,
    Building2,
    Trash2,
    ClipboardCheck,
    Scale,
    PackageSearch,
    UserRound,
    Users,
    IdCard,
    Bike,
    Clock,
    Truck,
    CalendarDays,
    Receipt,
    BarChart2,
    Store,
    UserCog,
    ShieldCheck,
    Landmark,
    Calculator,
    CalendarClock,
    Printer,
    Settings,
    ArchiveRestore,
    ScrollText,
} from 'lucide-react';

/**
 * Sidebar navigation. `route` is a Ziggy route name and also the permission:
 * an item shows when the admin may open that route (useCan). Items whose route
 * does not exist yet render disabled ("coming soon") so the menu is complete.
 */
export const navSections = [
    {
        section: 'Main',
        items: [
            { label: 'Dashboard', route: 'dashboard', icon: LayoutDashboard },
            { label: 'Point of Sale', route: 'pos.index', icon: ShoppingCart },
            { label: 'Orders', route: 'orders.index', icon: ClipboardList },
            { label: 'Tables', route: 'tables.floor', icon: LayoutGrid },
            { label: 'Kitchen Display', route: 'kitchen.index', icon: ChefHat },
        ],
    },
    {
        section: 'Menu',
        items: [
            { label: 'Categories', route: 'categories.index', icon: FolderTree },
            { label: 'Menu Items', route: 'menu-items.index', icon: UtensilsCrossed },
            { label: 'Ready Items', route: 'ready-items.index', icon: Package },
            { label: 'Add-on Groups', route: 'modifier-groups.index', icon: ListPlus },
            { label: 'Kitchen Stations', route: 'kitchen-stations.index', icon: Flame },
            { label: 'Deals', route: 'deals.index', icon: BadgePercent },
            { label: 'Discounts', route: 'discounts.index', icon: Percent },
        ],
    },
    {
        section: 'Inventory',
        items: [
            { label: 'Raw Materials', route: 'raw-materials.index', icon: Wheat },
            { label: 'Stock Ledger', route: 'stock-ledger.index', icon: History },
            { label: 'Purchases', route: 'purchases.index', icon: FileText },
            { label: 'Suppliers', route: 'suppliers.index', icon: Building2 },
            { label: 'Waste', route: 'waste.index', icon: Trash2 },
            { label: 'Stock Counts', route: 'stock-counts.index', icon: ClipboardCheck },
            { label: 'Pending Consumption', route: 'consumptions.pending', icon: Scale },
            { label: 'Low Stock', route: 'low-stock.index', icon: PackageSearch },
            { label: 'Units', route: 'units.index', icon: Ruler },
        ],
    },
    {
        section: 'People',
        items: [
            { label: 'Customers', route: 'customers.index', icon: UserRound },
            { label: 'Employees', route: 'employees.index', icon: Users },
            { label: 'Designations', route: 'designations.index', icon: IdCard },
            { label: 'Riders', route: 'riders.index', icon: Bike },
        ],
    },
    {
        section: 'Operations',
        items: [
            { label: 'Shifts', route: 'shifts.index', icon: Clock },
            { label: 'Deliveries', route: 'deliveries.index', icon: Truck },
            { label: 'Reservations', route: 'reservations.index', icon: CalendarDays },
            { label: 'Expenses', route: 'expenses.index', icon: Receipt },
            { label: 'Reports', route: 'reports.index', icon: BarChart2 },
        ],
    },
    {
        section: 'Administration',
        items: [
            { label: 'Branches', route: 'branches.index', icon: Store },
            { label: 'Admin Accounts', route: 'admins.index', icon: UserCog },
            { label: 'Roles & Permissions', route: 'roles.index', icon: ShieldCheck },
            { label: 'Bank Accounts', route: 'bank-accounts.index', icon: Landmark },
            { label: 'Cash Counters', route: 'counters.index', icon: Calculator },
            { label: 'Shift Types', route: 'shift-types.index', icon: CalendarClock },
            { label: 'Printers', route: 'printers.index', icon: Printer },
            { label: 'Settings', route: 'settings.index', icon: Settings },
            { label: 'Recycle Bin', route: 'trash.index', icon: ArchiveRestore },
            { label: 'Activity Log', route: 'activity.index', icon: ScrollText },
        ],
    },
];
